config/routes.rb
DomAccount::Application.routes.draw do
  resources :home

  match "/auth/wanliuid/callback" , :to => "sessions#new"
  match '/users/logout', :to => "sessions#destroy"

  root :to => 'home#index'

end

app/models/home.rb
class Home
  include Mongoid::Document
end

app/models/user.rb
class User
  include Mongoid::Document
  attr_accessible :uid, :login, :first_name, :last_name

  field :uid, type: String
  field :login, type: String
  
end

app/controllers/application_controller.rb
require 'net/http'

class ApplicationController < ActionController::Base
  include ApplicationHelper
  protect_from_forgery

  helper_method :login_required

  def login_required        
    if !current_user                
      respond_to do |format|    
        format.js{
          response_headers
          render :js => "ok".to_json } 
        format.html{ 
          redirect_to '/auth/wanliuid'  }        
        format.json {
          render :json => { 'error' => 'Access Denied' }.to_json   }
      end
      return false
    end
  end

  # def current_user
  #   return nil unless session[:user]
  #   session[:user]
  # end

  private
  def response_headers    
    options = auth_params
    response.headers["sso_auth_url"] = authorize_url
    response.headers["sso_auth_params"] = options.to_json
    foreg_state(options)    
  end

  def wanliu_omniauth_options     
    OmniAuth::Strategies::WanliuId.default_options.client_options 
  end

  def auth_params
    {
      :response => "code",
      :client_id =>  Rails.application.config.sso_app_id,
      :redirect_uri => "#{request.env["REQUEST_URI"]}auth/wanliuid/callback",
      :state => SecureRandom.hex(24)      
    }
  end

  def foreg_state(options)
    session["omniauth.state"] = options[:state]  
  end

  def authorize_url
    wanliu_omniauth_options.authorize_url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # before_filter :has_syn_login, :only => [:new]
  before_filter :login_required, :only => [:index]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all

    respond_to do |format|      
      format.html # index.html.erb
      format.json { render json: @homes }
    end
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
    @home = Home.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @home }
    end
  end

  # GET /homes/new
  # GET /homes/new.json
  def new    
    @home = Home.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @home }
    end
  end

  # GET /homes/1/edit
  def edit
    # @home = Home.find(params[:id])
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(params[:home])

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render json: @home, status: :created, location: @home }
      else
        format.html { render action: "new" }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /homes/1
  # PUT /homes/1.json
  def update
    @home = Home.find(params[:id])

    respond_to do |format|
      if @home.update_attributes(params[:home])
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home = Home.find(params[:id])
    @home.destroy

    respond_to do |format|
      format.html { redirect_to homes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new                      
        omniauth = env['omniauth.auth']                
        user = User.where(:uid => omniauth['uid']).first
        if not user        
          user = User.new(:uid => omniauth['uid'])
        end
        user.login = omniauth['info']['email']               
        user.save
        session[:user_id] = omniauth

        flash[:notice] = "Successfully logged in"        
        respond_to do | format |
            format.js{ 
                render :js => "alert('success request!')"  }
            format.html{
                redirect_to root_path }            
        end
    end

    def destroy
        session[:user_id] = nil
        
        respond_to do | format |
            format.js{ 
                render :js => "alert('success clear session !');" }
            format.html{
                redirect_to new_home_path  }            
        end        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    return nil unless session[:user_id]
    @current_user ||= User.where(:uid => session[:user_id]['uid']).first
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/application/_auth.js.erb
alert("<%= sso_provider_url %>/")

app/views/home/edit.html.erb
<script type='text/javascript'>
    // window.addEventListener("message", function(){
    //  console.log("click event  ...");
    //  alert(1);
    // })

    pm.bind("message", function(){
        console.log("click event  。。。");
        alert(1);
    })
    
//  window.postMessage("hello", "http://localhost:3000/home/new")
    console.log("bind event  ...")
</script>

app/views/home/new.html.erb
<iframe src="http://localhost:3002/accounts/login" id='dom1' name='dom1'></iframe>
<iframe src="/home/1/edit" id='dom2' name='dom2'></iframe>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DomAccount</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application", "postmessage" %>
  <%= csrf_meta_tags %>
  <style type='text/css'>
     body{
        margin : 0px;
        padding : 0px;
     }

     .head{
        padding: 10px 0px 10px 0px;
        width:100%;
        background-color: #DDD;
     }

     .login, .logout, .ajax_logout, .ajax_request{
        margin-left: 20px;
     }


  </style>
</head>

<body>
<div class='head'>
  <span class='login'>    
    <% if current_user.nil? %>
        <a href='/auth/wanliuid'>登陆</a>
    <% else %>
        <a class='user_login' href='javascript:void(0)'><%= current_user.login %></a>
        <a href="<%=users_logout_path %>" class='logout'>退出</a>
        <a href="javascript:void(0)" class='ajax_logout'>ajax清空session</a>
        <a href="javascript:void(0)" class='ajax_request'>ajax请求</a>
    <% end %>
  </span>
</div>
<%= yield %>
</body>
</html>

<script type="text/javascript">
  $(".ajax_logout").click(function(){
    $.get("<%= users_logout_path %>")
  })

  $(".ajax_request").click(function(){
    $.get("/")
  })
</script>